import { FuturesAsset } from '../types/futures';

export const INITIAL_FUTURES_ASSETS: FuturesAsset[] = [
  // --- CRYPTO FUTURES (20X) ---
  {
    id: 'fut_btc',
    name: 'Bitcoin (20X Futures)',
    symbol: 'BTC/USDT',
    tvSymbol: 'BINANCE:BTCUSDT',
    category: 'Crypto',
    price: 78370.00,
    change24h: -0.92,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_eth',
    name: 'Ethereum (20X Futures)',
    symbol: 'ETH/USDT',
    tvSymbol: 'BINANCE:ETHUSDT',
    category: 'Crypto',
    price: 2470.50,
    change24h: -0.78,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_sol',
    name: 'Solana (20X Futures)',
    symbol: 'SOL/USDT',
    tvSymbol: 'BINANCE:SOLUSDT',
    category: 'Crypto',
    price: 102.85,
    change24h: -0.90,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_bnb',
    name: 'Binance Coin (20X Futures)',
    symbol: 'BNB/USDT',
    tvSymbol: 'BINANCE:BNBUSDT',
    category: 'Crypto',
    price: 751.20,
    change24h: 1.50,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_xrp',
    name: 'Ripple (20X Futures)',
    symbol: 'XRP/USDT',
    tvSymbol: 'BINANCE:XRPUSDT',
    category: 'Crypto',
    price: 1.3995,
    change24h: 0.08,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 4,
    currencySymbol: '$',
  },
  {
    id: 'fut_doge',
    name: 'Dogecoin (20X Futures)',
    symbol: 'DOGE/USDT',
    tvSymbol: 'BINANCE:DOGEUSDT',
    category: 'Crypto',
    price: 0.08935,
    change24h: -1.25,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_ada',
    name: 'Cardano (20X Futures)',
    symbol: 'ADA/USDT',
    tvSymbol: 'BINANCE:ADAUSDT',
    category: 'Crypto',
    price: 0.2187,
    change24h: -0.80,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 4,
    currencySymbol: '$',
  },

  // --- FOREX FUTURES (20X) ---
  {
    id: 'fut_eurusd',
    name: 'EUR / USD (20X Futures)',
    symbol: 'EUR/USD',
    tvSymbol: 'FX:EURUSD',
    category: 'Forex',
    price: 1.16235,
    change24h: 0.01,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_gbpusd',
    name: 'GBP / USD (20X Futures)',
    symbol: 'GBP/USD',
    tvSymbol: 'FX:GBPUSD',
    category: 'Forex',
    price: 1.35560,
    change24h: 0.11,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_usdjpy',
    name: 'USD / JPY (20X Futures)',
    symbol: 'USD/JPY',
    tvSymbol: 'FX:USDJPY',
    category: 'Forex',
    price: 153.805,
    change24h: -0.34,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 3,
    currencySymbol: '¥',
  },
  {
    id: 'fut_usdinr',
    name: 'USD / INR (20X Futures)',
    symbol: 'USD/INR',
    tvSymbol: 'FX_IDC:USDINR',
    category: 'Forex',
    price: 94.808,
    change24h: 0.35,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.03,
    precision: 3,
    currencySymbol: '₹',
  },
  {
    id: 'fut_audusd',
    name: 'AUD / USD (20X Futures)',
    symbol: 'AUD/USD',
    tvSymbol: 'FX:AUDUSD',
    category: 'Forex',
    price: 0.72275,
    change24h: 0.12,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 5,
    currencySymbol: '$',
  },
  {
    id: 'fut_gbpjpy',
    name: 'GBP / JPY (20X Futures)',
    symbol: 'GBP/JPY',
    tvSymbol: 'FX:GBPJPY',
    category: 'Forex',
    price: 208.520,
    change24h: -0.22,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 3,
    currencySymbol: '¥',
  },

  // --- INDIAN MARKETS FUTURES (20X) ---
  {
    id: 'fut_nifty',
    name: 'NIFTY 50 (20X Futures)',
    symbol: 'NIFTY',
    tvSymbol: 'NSE:NIFTY',
    category: 'Indian',
    price: 23635.10,
    change24h: -0.61,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_banknifty',
    name: 'BANK NIFTY (20X Futures)',
    symbol: 'BANKNIFTY',
    tvSymbol: 'NSE:BANKNIFTY',
    category: 'Indian',
    price: 56777.55,
    change24h: -0.54,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_reliance',
    name: 'Reliance Industries (20X)',
    symbol: 'RELIANCE',
    tvSymbol: 'NSE:RELIANCE',
    category: 'Indian',
    price: 1294.90,
    change24h: -1.11,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_tatamotors',
    name: 'Tata Motors (20X Futures)',
    symbol: 'TATAMOTORS',
    tvSymbol: 'BSE:TMCV',
    category: 'Indian',
    price: 455.95,
    change24h: -0.69,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_hdfcbank',
    name: 'HDFC Bank (20X Futures)',
    symbol: 'HDFCBANK',
    tvSymbol: 'NSE:HDFCBANK',
    category: 'Indian',
    price: 703.00,
    change24h: -1.06,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },
  {
    id: 'fut_infosys',
    name: 'Infosys (20X Futures)',
    symbol: 'INFY',
    tvSymbol: 'NSE:INFY',
    category: 'Indian',
    price: 1082.00,
    change24h: -0.51,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.05,
    precision: 2,
    currencySymbol: '₹',
  },

  // --- COMMODITIES FUTURES (20X) ---
  {
    id: 'fut_gold',
    name: 'Gold (XAU/USD - 20X)',
    symbol: 'GOLD',
    tvSymbol: 'TVC:GOLD',
    category: 'Commodities',
    price: 4400.50,
    change24h: -0.66,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
  {
    id: 'fut_silver',
    name: 'Silver (XAG/USD - 20X)',
    symbol: 'SILVER',
    tvSymbol: 'TVC:SILVER',
    category: 'Commodities',
    price: 66.25,
    change24h: 0.08,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 3,
    currencySymbol: '$',
  },
  {
    id: 'fut_crude',
    name: 'Crude Oil (WTI - 20X)',
    symbol: 'CRUDEOIL',
    tvSymbol: 'NYMEX:CL1!',
    category: 'Commodities',
    price: 92.75,
    change24h: 1.40,
    leverage: 20,
    minMargin: 100,
    maxMargin: 5000,
    takerFeePercent: 0.04,
    precision: 2,
    currencySymbol: '$',
  },
];
